threefoldtech/tfgrid-sdk-dart

packages/tfchain_client/bin/tfchain_client.dart
packages/tfchain_client/lib/src/balances.dart
packages/tfchain_client/lib/src/client.dart
packages/tfchain_client/lib/src/contracts.dart
packages/tfchain_client/lib/src/twins.dart
packages/tfchain_client/lib/tfchain_client.dart

Get the result after applying extrinsic

---

packages/tfchain_client/bin/tfchain_client.dart
packages/tfchain_client/lib/src/client.dart

Apply better client interface using getters

---

packages/tfchain_client/lib/src/client.dart
packages/tfchain_client/lib/src/error_mapper.dart
packages/tfchain_client/lib/src/utils.dart
packages/tfchain_client/lib/tfchain_client.dart

Add error mapper to the tfchain client

---

packages/signer/pubspec.yaml
packages/tfchain_client/README.md
packages/tfchain_client/lib/tfchain_client.dart
packages/tfchain_client/pubspec.lock
packages/tfchain_client/pubspec.yaml
packages/tfchain_client/test/contracts_test.dart
packages/tfchain_client/test/farms_test.dart
pubspec.lock
pubspec.yaml

- Updated importing signer package to be from github.
- Fix versions of both signer and tfchain.

Update importing Signer pkg to be from github

---

packages/gridproxy_client/bin/gridproxy_client.dart
packages/gridproxy_client/lib/models/nodes.dart
packages/gridproxy_client/lib/src/nodes.dart

[ticket link](https://github.com/codescalers/tfgrid-sdk-dart/issues/42)

feat: implement node module

---

packages/gridproxy_client/bin/gridproxy_client.dart
packages/gridproxy_client/lib/gridproxy_client.dart
packages/gridproxy_client/lib/models/twins.dart
packages/gridproxy_client/lib/src/client.dart
packages/gridproxy_client/lib/src/twins.dart

[GridProxy twin implementation ](https://github.com/codescalers/tfgrid-sdk-dart/issues/48)

Tfchain gridproxy twins

---

packages/gridproxy_client/bin/gridproxy_client.dart
packages/gridproxy_client/lib/gridproxy_client.dart
packages/gridproxy_client/lib/models/stats.dart
packages/gridproxy_client/lib/src/client.dart
packages/gridproxy_client/lib/src/stats.dart

[Stats gridproxy](https://github.com/codescalers/tfgrid-sdk-dart/issues/50)

Stats implementation

---

pubspec.lock
pubspec.yaml

Reverts codescalers/tfgrid-sdk-dart#37

Revert "Bump melos from 4.1.0 to 6.0.0"

---

.github/ISSUE_TEMPLATE/bug_report.yml

[bug report issue template ticket ](https://github.com/codescalers/tfgrid-sdk-dart/issues/54)

update: bug report issue template

---

.github/ISSUE_TEMPLATE/bug_report.yml

fix the bug_report template not working
changed the about: key to the description: key
[#54 ](https://github.com/codescalers/tfgrid-sdk-dart/issues/54)

fix: bug_report template

---

.github/ISSUE_TEMPLATE/feature_request.yml

Added a feature request template.
https://github.com/codescalers/tfgrid-sdk-dart/issues/54

feat: feature request template

---

.github/workflows/coverage.yaml
README.md
packages/signer/pubspec.lock
packages/signer/pubspec.yaml
packages/tfchain_client/README.md
packages/tfchain_client/pubspec.lock
packages/tfchain_client/pubspec.yaml
pubspec.lock
pubspec.yaml

- Changed dart to `3.2.3`
- Changed flutter to `3.16.4`
- Updated path of tfchain to be imported from github.
- Added missing command in readme.
List of related issues

Main change dart flutter versions

---

packages/tfchain_client/lib/src/client.dart

Fix loading keypair for developers' accounts in tfchain client

Fix loading keypair for developers' accounts in tfchain client

---

CODEOWNERS
README.md

- Added redirection to stellar client from project readme.

add stellar_client in root readme file

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

- Include stellar client in issue templates.

add stellar client in issue templates

---

packages/tfchain_client/lib/models/dao.dart
packages/tfchain_client/lib/src/dao.dart

- Add proposal info model
- Update getting the action of the dao proposal

Update getting the action of the dao proposal

---

packages/stellar_client/lib/src/client.dart
packages/stellar_client/lib/stellar_client.dart
packages/tfchain_client/lib/src/twins.dart
packages/tfchain_client/lib/src/utils.dart

- Add method to get my twin in tfchain client
- Add getter for the private key in stellar client
- Fix hex regex in tfchain client
List of changes this PR includes
List of related issues

Some fixes and new methods for stellar and tfchain clients

---

packages/stellar_client/bin/stellar_client.dart
packages/stellar_client/lib/models/vesting_account.dart
packages/stellar_client/lib/src/client.dart
packages/stellar_client/lib/stellar_client.dart

- Check if the account is vesting account or not through threeflod service.
- Added `checkVestingAccount` function.
- https://github.com/codescalers/tfgrid-sdk-dart/issues/77

Check vesting accounts in Stellar Client

---

packages/stellar_client/lib/src/client.dart

- https://github.com/codescalers/tfgrid-sdk-dart/issues/91

Fix transferThroughThreefoldService in Stellar Client

---

packages/stellar_client/lib/src/client.dart
packages/stellar_client/lib/stellar_client.dart
packages/tfchain_client/lib/src/client.dart
packages/tfchain_client/lib/src/utils.dart

- add connection pool to the tfchain client
- change the transaction types
- add method to stellar client to load wallet from hex seed

Some fixes in the clients

---

packages/stellar_client/lib/models/transaction.dart
packages/stellar_client/lib/src/client.dart
packages/stellar_client/lib/src/types/transaction.dart
packages/stellar_client/lib/stellar_client.dart

- Add memo to PaymentOperationRequest
- Add TransactionType & ITransaction
- Create getMemoText fn
- https://github.com/codescalers/tfgrid-sdk-dart/issues/92

Add memo to PaymentOperationRequest

---

packages/graphql_client/pubspec.yaml
packages/gridproxy_client/pubspec.yaml
packages/stellar_client/pubspec.yaml
packages/tfchain_client/pubspec.yaml

Add coverage to pubspec.yaml in all packages
- https://github.com/codescalers/tfgrid-sdk-dart/issues/73

Fix codecov
